### PR TITLE
'gpstracker' module & 'call' module for Android

### PR DESCRIPTION
**Pull request by quentinhardy**
[+] New module named **_gpstracker_** for Android (tested on 4.4.2)
This module creates a new thread on the Android device for getting GPS position at regular intervals (by default each 15 seconds).
If the position has changed from the last GPS capture, the GPS position (latitude, longitude and date) is saved in memory process on the device. Consequently, while the device doesn't move, GPS data is not re-saved again (space-saving). Of course, when the device has been moved, new GPS data is saved.

**Even if the pupy process is disconnected from the controller**, the GPS Tracker **thread will continue to work** on the device. When the user wants, he can stop the thread.
At any time the user can download GPS positions stored in memory on the device (no file created).
If needed, the source code can be modified for saving GPS positions in a file on the device (see source code commented).

The controller will create 2 files on your computer: a **csv file** and a **KML** (Keyhole Markup Language) file.
The KML file can be used for **seeing the path of the device over time with Google Earth** for example. 
Of course, I think the **KML output can be improved** for better presentation in GIS (Geographic Information System) softwares.
```
>> run gpstracker --start 
[+] Tracking enabled. Get GPS position each 15 secds
>> run gpstracker --status 
[+] GPS tracking is enabled
>> run gpstracker --dump 
[+] 1 GPS positions
[+] GPS positions (.csv) saved in output/9faaaaaaaa151-u0_a152/gpsTraces.csv
[+] KML file created in output/9faaaaaaaa151-u0_a152/gpsTraces.kml
>> run gpstracker --stop
[+] Stopping GPS tracking... (can take 15 secds)
[+] Tracking stopped
```
See "run gpstracker -h" for more information.

**Notice** if you brutally close pupy on the device with "_session -K_", the GPS Tracker thread (created by the module on the device with the _--start_ command) will be not stopped. You **have to use the "--stop"** command before stopping the session controller side.

### CODE REVIEW

**Comment by jboss38** [comment]
Thanks for sharing, look very cool to me. 
Just a ramdom question;
There is a limit at saving at memory ? 
Or the data grow until the device get a overflow and crash ?

**Comment by quentinhardy** [comment]
I think data will grow until the app crashes.
It is why I can modify source code for saving data in a file...

**Comment by jboss38** [comment]
Yes i think adding a args to enable or not the 'save to file' could be nice. 

Like this, even If the device reboot you can keep tracking for multiples days.

**Comment by quentinhardy** [comment]
Done in the commit 69fa51de1ebda571ac1582e90535c5f0e6cbb3fd.
Now, **GPS data is stored in a file on device by default**.
Use -m option for GPS data in memory process only (no file created on the device).

**Comment by jboss38** [comment]
:+1: 
Nice one mate ;)

**Comment by quentinhardy** [comment]
These following commits are here for adding a new module named _call_:

- 89b455c5e36c8d44c6d32fd7f5b3e79600009764
- 2e5fcfbb5f03a40623bb77aeeb24e1aa77403f77

You can get all call details for the moment with this module.

**Comment by n1nj4sec** [comment]
wooot nice ! :D

**Pull request merged**
