### PR TITLE
'Handle Inheritance' method implemented in getsystem

### PR DESCRIPTION
**Pull request by quentinhardy**
Hello,

I have not searched a fix for the bug in the _getsystem_ module yet ([https://github.com/n1nj4sec/pupy/issues/704](https://github.com/n1nj4sec/pupy/issues/704)).

There is 'often' bugs in the _getsystem_ module with the _impersonation_ method...

That is why I have implemented a more **stable**, **simple** and 'safe' (against AV) method for becoming SYSTEM when you have admin rights on a Windows computer: "**Handle Inheritance**" (or "**Parent Process**" method). Some details here [https://movaxbx.ru/category/security/page/2/](https://movaxbx.ru/category/security/page/2/)

I think this method has been discovered by James Forshaw.

I have tested this 'Inheritance' method on wind10 x64 arch, from a x86 and x64 process. All works well.
I have not modified the source code of the "impersonation" method.

Now the user has to choose between the '_impersonation_' method (with a migration) or the '_Inheritance_' method in the _getsystem_ module when he would like to become SYSTEM.

### CODE REVIEW

**Comment by quentinhardy** [comment]
There is a problem with this pull request ?

**Comment by AlessandroZ** [comment]
Hi, 
Sorry to not merge your PR but some conflicts were present with the @alxchk [push](https://github.com/n1nj4sec/pupy/commit/16cbdf00d3a791f163b038736e377945e58a5eb8#diff-bc39408ddf40c6673480c28f5e34129d) and I didn't take the time to try it. 
I have tried the module without success. If you have an example of how you made it to work, it will be great. 
On Windows 8.1 and Windows 10, it never find a process with SYSTEM integrity level. When I do a print of all integrity level found, here is the output (same result on windows 10): 
```
>> sessions 
id  user  hostname  platform  release  os_arch  proc_arch  intgty_lvl  address      tags  
------------------------------------------------------------------------------------------
1   xxx   xxxx    Windows   8.1      AMD64    64bit      High        xx.xx.xx.xx        
>> getsystem -m inheritance -r
[%] The current pupy launcher is using a REVERSE connection (e.g. 'auto_proxy' or 'connect' launcher)
[%] Trying to configure for running the current executable on the target as SYSTEM
[%] Method 'Handle Inheritance' (Parent Method) chosen
[%] Getting information about all processes running on the target
[%] Searching a process with a 'SYSTEM' integrity level
1
1
1
Medium
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
Medium
1
Medium
1
1
Medium
Medium
Medium
1
1
Medium
Medium
1
High
1
1
1
1
1
>>
```
When I forced, the ppid to a system process, I got this: 
```
>> getsystem -m inheritance --ppid 528 -r 
[%] The current pupy launcher is using a REVERSE connection (e.g. 'auto_proxy' or 'connect' launcher)
[%] Trying to configure for running the current executable on the target as SYSTEM
[%] Method 'Handle Inheritance' (Parent Method) chosen
[%] Using the Parent Process method on the pid 528...
2018-11-26 10:18:31,379| (6, 'Descripteur non valide')

========= Remote Traceback (1) =========
Traceback (most recent call last):
WindowsError: [Error 6] Descripteur non valide

[-] (6, 'Descripteur non valide')
```

Please don't forget to run flake8 before doing a commit, otherwise, it would never pass travis checks.

Thanks :)

**Comment by AlessandroZ** [comment]
@alxchk, I don't have time to debug this error right now, but with high integrity session, I cannot get the integrity level of other processes. [OpenProcessToken](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/packages/windows/all/pupwinutils/security.py#L1810) always fails, so I get "1" as return value. 
With the same session, doing `>> ps -i`, on the process owner column, it's empty for all system processes. So as I put on my previous output, the module stops because it does not found any SYSTEM processes. 

When I get system (using other method), I can see every system processes and OpenProcessToken works so the inheritance method works (from system to system). 

I don't know if I'm the only one having this error but right now, I cannot use the inheritance getsystem method.

**Comment by alxchk** [comment]
You try the version before the merge or after?
I fixed some issues there during the merge, works for me with Win10.

But in my case there were always processes with System. So maybe your case is different.
Can you show ps or tasklist output (with owners)?

BTW original code didn't acquire SeDebugPrivilege. Try merged version first

**Comment by AlessandroZ** [comment]
I have tried after merging the code and I still have the same issue. 
Here is the output of ps: 
```
>> ps -i 
   0 NT AUTHORITY\SYSTEM   0%   0% {System Idle Process} 
   4 NT AUTHORITY\SYSTEM   0%   0% {System} 
  68                       0%   0% {Registry} 
 220                       0%   0% {WmiPrvSE.exe} 
 304                       0%   0% {smss.exe} 
 388                       0%   0% {csrss.exe} 
 456                       0%   0% {wininit.exe} 
 464                       0%   0% {csrss.exe} 
 524                       0%   0% {winlogon.exe} 
 560                       0%   0% {services.exe} 
 584                       0%   0% {lsass.exe} 
 648                       0%   0% {fontdrvhost.exe} 
 656                       0%   0% {fontdrvhost.exe} 
 672                       0%   1% {svchost.exe} 
 740                       0%   1% {svchost.exe} 
 768                       0%   0% {svchost.exe} 
 804                       0%   1% {svchost.exe} 
 868                       0%   2% {dwm.exe} 
 948                       0%   2% {svchost.exe} 
 960                       0%   1% {svchost.exe} 
 992                       0%   1% {svchost.exe} 
1008                       0%   2% {svchost.exe} 
1064                       0%   1% {svchost.exe} 
1184                       0%   0% {VBoxService.exe} 
1316                       0%   1% {Memory Compression} 
1424                       0%   0% {svchost.exe} 
1488                       0%   0% {svchost.exe} 
1512                       0%   0% {svchost.exe} 
1520                       0%   0% {svchost.exe} 
1596                       0%   0% {spoolsv.exe} 
1712                       0%   0% {svchost.exe} 
1772                       0%   0% {svchost.exe}
2604 DESKTOP\test   0%   4% C:\Windows\explorer.exe
.....
6956 AUTORITE NT\Système   0%   0% C:\Windows\System32\SearchFilterHost.exe 0 736 740 748 8192 744
....
```
And here is with tasklist:
```
>> shell_exec tasklist /v
Nom de l'image                 PID Nom de la sessio Num�ro de s Utilisation  �tat            Nom d'utilisateur                                  Temps proces Titre de la fen�tre                                                     
========================= ======== ================ =========== ============ =============== ================================================== ============ ========================================================================
System Idle Process              0 Services                   0         8 Ko Unknown         AUTORITE NT\Syst�me                                     0:30:04 N/A                                                                     
System                           4 Services                   0        92 Ko Unknown         N/A                                                     0:00:07 N/A                                                                     
Registry                        68 Services                   0     8�404 Ko Unknown         AUTORITE NT\Syst�me                                     0:00:01 N/A                                                                     
smss.exe                       304 Services                   0       916 Ko Unknown         AUTORITE NT\Syst�me                                     0:00:00 N/A                                                                     
csrss.exe                      388 Services                   0     4�236 Ko Unknown         AUTORITE NT\Syst�me                                     0:00:00 N/A                                                                     
wininit.exe                    456 Services                   0     3�624 Ko Unknown         AUTORITE NT\Syst�me                                     0:00:00 N/A                                                                     
csrss.exe                      464 Console                    1     3�840 Ko Running         AUTORITE NT\Syst�me                                     0:00:00 N/A                                                                     
winlogon.exe                   524 Console                    1     5�532 Ko Unknown         AUTORITE NT\Syst�me                                     0:00:00 N/A                                                                     
services.exe                   560 Services                   0     6�080 Ko Unknown         AUTORITE NT\Syst�me                                     0:00:01 N/A                                                                     
lsass.exe                      584 Services                   0    11�192 Ko Unknown         AUTORITE NT\Syst�me                                     0:00:01 N/A         
......
```
I will check why this happen, right now I don't have time to check it sorry. Just to let you know.

**Comment by AlessandroZ** [comment]
You were right, I needed to have SeDebugPrivilege to do it. 
But in your last merge, it was done on your code, maybe you didn't push it. Anyway, I added it but if you want to do it in another part of the code, feel free to change it. 

I added it on the "ps" module as well when we have high privilege only.

**Pull request merged**
