### PR TITLE
Save the keystrokes in a file

### PR DESCRIPTION
**Pull request by anonni**
save backup of recorded keys in a file, if anything happens like the terminal is accidentally closed or the system shuts down.

### CODE REVIEW

**Comment by void-in** [comment]
This is potentially a very dangerous operation. First, this change can only save the files in Linux based OS (~/ home directory syntax). Secondly it is leaving a file on the victim's hard drive that is not cleared afterwards. And thirdly, you never want to touch the disk.

**Comment by anonni** [comment]
but this is only saving the file in the attacker disk,  not the victi.
at which point the file is saved to disk of the victim ?

**Comment by void-in** [comment]
@anonni Sorry I commented without reading the code first. Regarding the file expansion of ~/ syntax, I think if you take a look at the file download module, it creates a temporary directory in the current working directory of puppy and then save the file there. I think you can do the same. The example code is https://github.com/n1nj4sec/pupy/blob/f83c2a36c1c3ec690d2ba682b69a523fe8e94571/pupy/modules/download.py#L19-L28

**Comment by anonni** [comment]
i think the last commit It is the simplest way
to save in the current directory.
i use `os.getcwd` to get the current directory

**Comment by anonni** [comment]
Now the file is saved in the current working directory.
I tested only on windows and linux
also I don't now if the code works the same in mac

**Comment by n1nj4sec** [comment]
thank's I integrated this feature in the "dev" branch but I had already made changes to the keylogger so it was to much pain to merge

**Pull request closed without merging**
