### PR TITLE
[Intention PR] Pupy comes back from war

### PR DESCRIPTION
**Pull request by alxchk**
This is pull request intention. Because a lot of changes it's very likely that some parts are broken. So this more like request for testing.

Major changes:
+ Core commit - 8bfae8bb507856fb5f313efbd0d85284c8779848
+ Linux build environment ! (04b3eb0f2c3a9781a16b91275bdd93b71f647b46)
+ New socks5/forwarder module based on pyuv. You can watch YouTube in browser via socks5 in pupy now! 
   It's very fresh, so there may be bugs. (8c35337379d71ef95f4bf008d8f5d9d5e0a18e37)
+ MemFD support (6bbee454ac056d6444cea9626d1deaa9b881e5bb). Really crazy thing!
+ Tonns of pupyimporter improvements. 
   * Introduce bundles (45ad9ccff6d892eeade15495bda1bc4f0c01760e, 128ec9bc53ba0a7865ba068f053029a3a28521d3,  ba9cdc7f8c1cf4bac8ae0775c9231691c4c5a5a6). Bundle is archive with python folder for supported targets (win/lin x86/amd64) which generated during buildenv.
   * Fix search paths (c11d2d7253a237331c6bf43905a9ab56f01e982c) 
   * Fix forced reload (1a3ad7bb60d36be1c9575078668096b1fe3d2bc9)
   * Don't try to upload garbage to client during module load (7dbfb5ae981b60acdaa29b020f445c61c372052c)
   * Improve build environments to build all known binary objects during buildenv, and remove all that garbage from repository (9569b8868af6f84d4d82c4c477582862b7ffd3eb, 9419bb200ad8db04a47f8e2760cce6be1ff5413a, 891d7aed0522ac6ccc71ceae7498d504a12bdae4, 7a89fab23839dbee99fb480d7bacb42339b7668e)
    * Try to omit manual package loading from the code, add dependencies to classes and reduce transfer size if possible (b732a93488840edcea8950cea82d7e5c9904a69f, a6a992eaefb26933621c84986bf1ffad60af927d, 638a6469a1823bf6e368068f16b050b2e4d54f24, f23b61e254ab0a7cf4f1760dd03c34aef824b198, 2a2f4f5d1a226cd8bd995c243073acfefcef9bae, 52c518a8d8974fcabc986412e3001ebdee840e86)
    * Add some kind of memimporter to pupyimporter without client (bb292072e8d323fc3269c8c7e5b668bd97d113bd)
+ Add UPnP IGD initial support (e320af34ae7c21c8123b002eb070b1aef86c4009)
+ Use LZMA as much as possible. Templates size about 2 times smaller now (8dc9232450266713167e6692573aa851d2f9cc56)
+ Remove packages which are not required during pupy initialization from templates (128666a1e0b38a4c3e7f8588477c4f538e98eddf, fc7d0253eccc7ab8e26e22d6934d9ef75b14dca3)
+ CNC metalauncher which works on top of DNS (34b3551e1fb0082e4b33db61ba22927afe7dd4c0, 308ebe2df64360b63c27789818a4e4a3dccb7d02)
+ PupyConfig class to place all config logic to one place (3a441f3d93ce85e37e33d923d8bc819e0d0150eb, 8a3dee31caabcfaaa36af38162de27b63a9b1424)
+ A lot of work to prevent pupy client to walk around FS, load modules and so on. Commits like this (248094d89dc5d9edb06b67c7d55693d1257bddd2) 

Minor changes:
+ Chunks for upload/download calculated from file size to improve speed. Up to 8 times faster in some cases now (569f741cfed6ea51d5f0308c7fc147f385aa9609).
+ Outgoing connections (to bind payload) uses same network workarounds. Latency improved for bind payloads (744a304eb594e66a19b803658fe5125504ed32a2) and other minor things (3fa6eb4ab29f50fb1b55b083e6563fd6313f5239).
+ Reuse session id numbers to keep them smaller (a39670a78fad5734f2b8c8808233822e5e08f3a3)
+ Various resources.zip optimizations (288aa030bfe3d5fef0d478354f8b3ce5bdd556ab)
+ Reduce path sizes (and also try to prevent leak of user info from pupysh modules - d7214db8f90db66030462114b54ded7b8560a9d7)
+ Remove garbage from uploaded packages (93ddf8015db1a77f58b47a2f63978d978a36e6e5)
+ Write bash history to /dev/null for bash (767eeb82c7aac62742de8067181da67ab60f24bc)
+ Load pywintypes properly (2a2e6d949febb2347893083b1c08595f34bd91cb)
+ Try to hind environment and argv0 in linux client (a31537968c6f2c224c6bfb05b6a0904ab48cac86, 45ac2bf02ed792d63ff9edc69e91f4743133c154)
+ Disable dumps, access and other things in linux client/user (e6b227f36ce3db0cb4dbb2f5d7373cd717c42322)
+ ECPV + RC4 transport (b089e69ac5af78cca67837d6f3aa2f5e5dd1158e)
+ New port scanner module (08fc22a93234405903d882c894661b252eb028ad)

.... and a lot of different fixes and new bugs

Known issues (regressions):
+ SSL transport can get crazy from time to time.
+ duplicate doesn't work on AMD64 
+ memory_execute on AMD64 fails on some binaries. pupy in that list =\
+ from time to time pupysh start eating 100% CPU. maybe have some relation to migration

Please note, new clients completely incompatible with old.

### CODE REVIEW

**Comment by jboss38** [comment]
Nice m8

**Comment by n1nj4sec** [comment]
is "socketserver" SocketServer from python std lib ?
from Traceback (most recent call last):
  File "./pupysh.py", line 36, in <module>
    from pupylib import PupyServer
  File "/home/me/partage/pupy/pupy/pupylib/__init__.py", line 7, in <module>
    from PupyDnsCnc import *
  File "/home/me/partage/pupy/pupy/pupylib/PupyDnsCnc.py", line 4, in <module>
    from network.lib.picocmd.server import *
  File "/home/me/partage/pupy/pupy/network/lib/picocmd/server.py", line 17, in <module>
    import socketserver
ImportError: No module named socketserver

**Comment by alxchk** [comment]
No. It turns out to be alias to 
```from SocketServer import *```
Likely comes with dnslib as dependency

**Comment by n1nj4sec** [comment]
ok, my python "future" package wasn't up-to-date

**Comment by n1nj4sec** [comment]
Could you push you next commits to the "unstable" branch ? thx :)
https://github.com/n1nj4sec/pupy/tree/unstable

**Comment by alxchk** [comment]
ERROR: Permission to n1nj4sec/pupy.git denied to alxchk.

:(

**Comment by n1nj4sec** [comment]
I meant pull request to my unstable branch not push sry !

**Pull request closed without merging**
