### PR TITLE
new updates

### PR DESCRIPTION
**Pull request by AlessandroZ**
Hi, 
- portfwd.py: for windows clients, it will open a port on the remove host (need to be admin) before trying to realize a port forwarding. Without this check, a pop up is prompt to the end user. 
- creds: all creds module will be on the "creds" category
- lazagne.py: a bug has been corrected while parsing the output. 
- killme: this feature has been removed

Alessandro

### CODE REVIEW

**Comment by AlessandroZ** [comment]
shell_exec: tested on linux and windows. Now you can: 
- run shell_exec "ps aux" 
- run shell_exec -s /bin/sh "ps aux"
getpid, getppid and ps modules work.

**Comment by AlessandroZ** [comment]
Last commit before my holidays. 

Lazagne is launched on memory. All modules are loaded as packages. It only works for Windows x86 processes (for x64 bits, it's possible to migrate to a 32 bits process before launching it). 
I have no time to do the same for x64 bits but I will do it later (I only have to put the good pyd and dll, lazagne modules will not change). 

For Linux, it will be harder because I saw that the tool does not manage ".so" files so it could take more time to me implemented. 
Have a nice day. 

Alessandro

**Comment by n1nj4sec** [comment]
Thank you ! I only took lazagne.py without merging everything to make a submodule instead of copying all the laZagne project. Tell me if everything works ok. All seems ok from my side except the web_history dll for IE that open a popup saying it needs MSVCR100 but the passwords are well retrieved

**Comment by AlessandroZ** [comment]
I  have made some changes on Lazagne. You should not get the error message again. No more files are written on the disk (for more information: https://github.com/AlessandroZ/LaZagne/blob/master/CHANGELOG). 
However, I changed as well the arborescence of the files (it should not change anymore, at least for windows), so you should changed the symbolic link too. See you !

**Pull request closed without merging**
