### PR TITLE
CredDump module

### PR DESCRIPTION
**Pull request by DeveloppSoft**
Added the creddump module which:
 - download the hives
 - run the 'creddump' software

Changes:
 - credump lib
 - creddump module
 - license for the lib

### CODE REVIEW

**Comment by n1nj4sec** [comment]
Thank you ! I had to make some changes to make it work on my configuration (tested on a win7). Can you tell me if it still works on yours ?

**Comment by DeveloppSoft** [comment]
@n1nj4sec will test, unfortunately I do not have access my win 8 computer ATM.
+ why did you close it?

**Comment by n1nj4sec** [comment]
@DeveloppSoft I closed the PR because it didn't close automatically after I merged. I only merged the first commit without the full library code to avoid having to review all the code in case you backdoored it ;)

**Comment by n1nj4sec** [comment]
I can be a little paranoid, nothing personal ;)

**Comment by DeveloppSoft** [comment]
@n1nj4sec that's okay I can understand :smile:
If you review the code, you will see there is no backdoor :smirk: but I
think it is a good things to take precautions...

**Pull request closed without merging**
