### PR TITLE
Added ability to add redundant server hosts.  --host argument can be …

### PR DESCRIPTION
**Pull request by ChristopherShawn**
…overloaded for multiple servers.  Each one will be tried in order 3 times before moving onto the next.  Then the whole list will be looped over as it used to loop over the single host.

### CODE REVIEW

**Comment by NeverMine17** [comment]
Maybe you can do it like that --host ip1,ip2,ip3 ?

**Comment by ChristopherShawn** [comment]
I did it that way at first, but with argparse, the code is cleaner with --host, --host, --host

**Comment by quentinhardy** [comment]
Very useful. Thank you for the idea.

**Comment by n1nj4sec** [comment]
merged into unstable

**Pull request closed without merging**
