### PR TITLE
Mimikatz

### PR DESCRIPTION
**Pull request by AlessandroZ**
- Check-Vm has been written in python and the powershell version has been deleted.
- mimikatz and mimikatz_powershell have been concatenate into one single module. The idea was to parse the output of mimikatz to add credentials found into the database as it was done on the powershell version. It works very well, the only thing is when you launch mimikatz in lots of hosts, it asks you to press enter at the end (so if you have many hosts, it could be very annoying). I had to use the interactive mode to retrieve the output, maybe there is a way to simulate this action. However, except that, it works well. 

Note: I had many duplicated values into the creds database, I think the check should be changed (https://github.com/n1nj4sec/pupy/blob/unstable/pupy/pupylib/utils/credentials.py#L64).

### CODE REVIEW

**Comment by alxchk** [comment]
mimikatz_powershell usually useless on recent win10 stations. Why to use it anyway?

**Comment by AlessandroZ** [comment]
I agree that if the mimikatz binary could be injected in memory, the powershell version is not necessary. I liked the powershell version because you can retrieve password from a 32 bit process on a 64 bit host (it launches a 64 bit powershell instance). I think it could be done using the memoryexec module using the "[suspended_proces](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/packages/windows/all/pupwinutils/memexec.py#L83)" option but I still have some problem of compatibility [here](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/lib/windows/memory_exec.py#L18).

**Comment by AlessandroZ** [comment]
This [ugly fixe](https://github.com/n1nj4sec/pupy/pull/487/commits/4d7752c2d097ef8040cc9bc9f2967be499768aa2#diff-2063e7d53836b3a9936e3614e9075c8fR70) simulates the enter key pressed once the execution is done. 
I think it's important to do it (using this technic or another one), because if you launch mimikatz on many hosts, it could be very painful to press "enter" many times. 

However, this technic requires to install [PyUserInput](https://github.com/SavinaRoja/PyUserInput) and Xlib: 
`sudo apt-get install  python-xlib`

**Comment by AlessandroZ** [comment]
@alxchk, I have commented your code to insert into the database because it stores duplicated values. I tried to debug your code but I cannot found a way. If you find a way, remove my code :)

**Comment by AlessandroZ** [comment]
@alxchk, I have tried the memstrings module without success. I don't know if I miss something or if there is something to fix. I tried:
`run memstrings -p <pid> -S`

I have no return output and debugging the module, it seems to never enter on the for [loop](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/packages/all/memstrings.py#L47). So maybe, the pattern does not work for all processes. I have tried it on Windows and Linux. Do I miss something ? Thanks for your help.

**Comment by alxchk** [comment]
Memstrings is broken on windows but should work on linux (if you have ptrace or root privilege)

**Comment by alxchk** [comment]
Next month I should have some time and fix all the things in pupy :))

**Comment by AlessandroZ** [comment]
Awesome, thanks you !! :)

**Comment by AlessandroZ** [comment]
Note that on the tag [on_connect] in the configuration file, the action should have a different name, otherwise only one action is performed. 

It has to be like that: 

```
[on_connect]
run_module1 = lazagne
run_module2 = gather/keylogger start
```

**Pull request merged**
