### PR TITLE
[ADD] Screenshot auto migrate option

### PR DESCRIPTION
**Pull request by 1mm0rt41PC**
Basic usage: run gather/screenshot --migrate C:\\windows\\explorer.exe
will migrate from "NT authority" to explorer user and take a screenshot of the user session.

### CODE REVIEW

**Comment by killercoderz4** [comment]
God say sir. I think the biggest challenge with puppy I lack of persistence. In built persistence is needed for all payloads. I use power shell one liner. It works great but once I restart my VMware I loose session. By the way I implemented registry method of persistence and it fails to work

**Comment by Strazzom** [comment]
This needs to be merged, as it is impossible to take screenshots from the NT process. I have worked around this by migrating to explorer in a second session, but this is a less than elegant solution.

**Comment by alxchk** [comment]
Personally I don't like this. Migration changes the state, and at my opinion this should be done explicitly.

**Comment by AlessandroZ** [comment]
Moreover, some AV detects really well migrations, it should be done manually to control what is happening.

**Comment by Strazzom** [comment]
@AlessandroZ This is true, but it is not ideal to have multiple listeners connecting to the network. Each session (correct me if I am wrong) uses its own connection. That means if one were to have two sessions (SYSTEM and Admin) then there would be twice as much network traffic.

I am not sure how hard it would be to implement, but Cobalt Strike has a feature where all privilege escalations still use the original listener for network connectivity, thereby keeping network traffic to a minimum.

Their description of it can be read here: https://www.cobaltstrike.com/help-smb-beacon

**Comment by alxchk** [comment]
> thereby keeping network traffic to a minimum.

Pupy is *very* inefficient in meaning of network traffic. Also this patch simply do the same - this is just migration with new connection.

**Comment by AlessandroZ** [comment]
Hi @Strazzom, sorry for my late answer. 

Sharing the same session won't reduce the network traffic. However, Cobalt strike allows the user to change the hearbeat rate of the client when you don't use your client at all. I think, this could be a good idea to implement it. It's like "hibernating" all sessions not used. 

However, I think sharing the same session is a wonderful idea for pivoting into a network. Right now, pivoting can be done using port forwarding but it's not as easy as it could be. A port should be openned on the remote host. Cobalt strike use named pipe to communicate between sessions which does not require any new open port listening. I don't know right now how hard it could be to implement it, but the idea is cool. I knew that all actions like bypassing uac or becoming system was not possible using a tcp bind payload, it has been implemented now but a new port is open and I think it's not the best way. 

Moreover, AV complicates a little bit the way to use these modules. To elevate our privilege, a dll or an exe should be written and executed on the remote host. Some AV will scan all new exe launched on the disk which means if you execute these modules, you will be scanned again (which could be weird for a user), sometimes migrating to a process could be triggered too (which is used by default on these modules). That's why, I have added the possibility to [restart](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/getsystem.py#L35) the same process if we use an exe as payload, or a [powershell](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/getsystem.py#L36) version (which that bypass most AV). 
I don't know how Cobalt strike deploys new sessions without beeing trigger by AV. We should add some way to allow a user to use its own packer or way to generate custom exe / or to encrypt dlls. It could simplify some modules like getsystem and bypass uac because custome exe or dlls could be written on the disk without being trigger by AV (like Cobalt Strike?).

**Comment by Strazzom** [comment]
@AlessandroZ I have been wondering about custom packers and crypters myself. Some automated script to run a given payload or DLL through something like Veil shouldn't be that hard to implement.

**Pull request closed without merging**
