### PR TITLE
Default credentials scanner

### PR DESCRIPTION
**Pull request by AlessandroZ**
It's a new module very useful for red team assessment. It allows to scan a host for default credentials (manage web interface, ftp anonymous, etc.). 
It could be used for example to check default credentials on tomcat, weblogic, websphere, etc, interfaces. 

I tried to work to add the main github project on pupy but I have wait too long the creator of the project and nothing happened. I had done a pull request which has never been accepted, so I prefer to add my fork as submodule to be used as pupy module. 

I have tested it with the windows remote session and it worked well. However, with a Linux binary, I have an import error and I cannot understand which one is wrong or missing. I don't build a debug binary so maybe you could fix it easily.

### CODE REVIEW

**Comment by AlessandroZ** [comment]
The first explicit error that I had, was that the module "unicodedata" was missing on my linux host. It used when the OpenSSL import is done (visible in pupylib/PupyPackagesDependencies.py). 
I comment this line, but it should produce the import problem.

**Comment by n1nj4sec** [comment]
I have trouble making this work, it seems your fork is broken
```
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 305, in _dispatch_request
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 535, in _handle_call
  File "changeme/core.py", line 101, in run_changeme
  File "changeme/scan_engine.py", line 16, in scan
  File "changeme/scanners/http.py", line 73, in scan
NameError: global name 'fp' is not defined
```
I also tried the ztgrace master but I have tons of errors :/

**Comment by AlessandroZ** [comment]
This error should be fixed, I have done a new commit on the project. 

I have tested it again and I have some imports problem at first that I didn't have using previous pupy version but the module is well loaded and it works. Executing the second time no module errors are loaded. 

```
>> run changeme -c web --name tomcat --target 192.168.0.10
.... (some imports errors)
ImportError: cannot import name MozillaCookieJar
[-] Error loading package asn1crypto._perf._big_num_ctypes (asn1crypto/_perf/_big_num_ctypes.pyo pkg=False) : Traceback (most recent call last):
  File "<string>", line 281, in load_module
  File "C:\users\me\temp\pip-build-0shywm\asn1crypto\asn1crypto\_perf\_big_num_ctypes.py", line 33, in <module>
LibraryNotFoundError: The library libcrypto could not be found
WARNING:root:Path contains unsafe binary objects: _speedups.so
[-] Error loading package requests.packages.urllib3.contrib.socks (requests/packages/urllib3/contrib/socks.pyo pkg=False) : Traceback (most recent call last):
  File "<string>", line 281, in load_module
  File "/home/joe/.local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/socks.py", line 27, in <module>
ImportError: No module named socks
Loaded 1 default credential profiles
Loaded 17 default credentials

[!] passwords not found
>> run changeme -c web --name tomcat --target 127.0.0.1
Loaded 1 default credential profiles
Loaded 17 default credentials

[+] Apache Tomcat
[+] URL: http://127.0.0.1:8080/manager/html
[+] tomcat/tomcat

[+] Apache Tomcat
[+] URL: http://127.0.0.1:8080/manager/html
[+] ovwebusr/OvW*busr1

[+] Passwords stored on the database
```

I would prefer to work using the real "changeme" project from ztgrace but I had rebuilt everything to be used with pupy, and my pull request had not been accepted. Moreover, lots of external lib have been added such as shodan that would not be very interesting to add on pupy. 

If one day, he does everything to be compatible with pupy, we will change the submodule location to his repository without problem.

**Comment by quentinhardy** [comment]
Good thing when you would like pivoting to another network unreachable directly...

**Pull request merged**
