### PR TITLE
Creds output

### PR DESCRIPTION
**Pull request by AlessandroZ**
I have changed the creds output to have a humain readable output. 
Now, it is possible to search into passwords (word could be "hash", "plaintext", an uid, or anything that could be in the login, the password / hash, or the url). 
`creds -s <word>`

To retrieve creds by host
`creds --sort`

### CODE REVIEW

**Comment by AlessandroZ** [comment]
I have changed the dictionary used to store passwords, it was more easy to retrieve values on the json. So please, update the lazagne submodule to my last commit. 
Thanks.

**Comment by AlessandroZ** [comment]
Now lazagne works for linux host. The shared library are well loaded on the remote host. 

Please add these lib to linux package directory:
- Python file
```
packages/linux/all/dbus/
packages/linux/all/etree/
packages/linux/all/lazagne/
```

- Shared library
```
crypt.so
_dbus_bindings.so
_elementtree.so
pyexpat.so
_sqlite3.so
```

Here is what my directory looks like

```
pupy/pupy/packages/linux/all$ tree -L 1
.
├── crypt.so
├── dbus
├── _dbus_bindings.so
├── _elementtree.so
├── etree
├── keylogger.py
├── lazagne
├── linux_stealth.py
├── persistence.py
├── ptyshell.py
├── pupystealth
├── pyexpat.so
└── _sqlite3.so
```
**Note:** This technic works great on using binary payload, however, using a classic python file, it fails. I don't know how the python file is generated but the client code seems different. Here is the error:

```
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "<memimport>/rpyc/core/protocol.py", line 305, in _dispatch_request
  File "<memimport>/rpyc/core/protocol.py", line 535, in _handle_call
  File "<string>", line 118, in load_module
NameError: name '_memimporter' is not defined
```

**Note 2:** The binary payload works only on my host (my VMs libc versions are older so it does not work), so I didn't test on many hosts. I have done my test only on a x64 machine.

**Comment by n1nj4sec** [comment]
yes, _memimporter is builtin into both linux and windows payloads and allow to load .pyd/.so from memory. It is however unavailable for pure python files. I guess we could build it as a .so and drop it on disk in case of .py payload but the must would be to rewrite it using ctypes as it would be totally stealth :)

**Comment by n1nj4sec** [comment]
what is etree and where did you grab it ? I can't find it on pypi nor my package manager

**Comment by AlessandroZ** [comment]
etree is for xml. This is weird because, the main directory is xml. If I put etree and not xml, I suppose I had my reason lol.  
Anyway, it's on the xml repo and it I use it on lazagne like that: 
`import xml.etree.cElementTree as ET`

And here is where it is located on the disk
`# /usr/lib/python2.7/xml/etree/ElementTree.pyc matches /usr/lib/python2.7/xml/etree/ElementTree.py`

**Comment by n1nj4sec** [comment]
If you imported it like in your example, i guess the directory is not used
And since a recent commit you don't even have to put standard libraries in the packages/ directory, pupy load_packages() function can grab them from your server's python path automatically if not found in the packages/ repository

**Comment by AlessandroZ** [comment]
This lib is used many times on lazagne to parse xml: https://github.com/AlessandroZ/LaZagne/search?utf8=%E2%9C%93&q=+xml.etree.cElementTree+

However, you may have right saying that is not the directory "xml" which is used, maybe it is the lib installed on my OS. However, it's weird because, doing tests, everytime, I had module errors, and I had to use load_package manually on the code to correct the problem. That's why I explicitly say which import to load. 

Try without adding the xml lib, maybe no errors will be prompted, but I don't know how it could find the cElementTree lib.

**Comment by alxchk** [comment]
I merged creds branch to my repo - 56df436d
You can try to use it. I tested this on W10/AMD64, CentOS5, Ubuntu 9.04, Gentoo ~amd64.
I put to repo missing modules (crypto.so, _sqlite3.so, _scandir.so, _elementtree.so), dbus is embedded to client template. Modules built on woody/x86 and etch/amd64. 
Notes about binary compatibility can be found here - https://github.com/alxchk/pupy/blob/master/client/sources-linux/NOTES

**Comment by n1nj4sec** [comment]
tell me if I'm wrong, but I think this is merged ?

**Comment by AlessandroZ** [comment]
You're right, the file has already been merged. I have added the symbolic link for linux. 

Before to close the pull request, I have tried lazagne on linux using your (@alxchk) x64 linux binary and I had an error loading the sqlite3 dependency. Here is the stacktrace: 
```
  File "<string>", line 116, in load_module
  File "<string>", line 97, in load_module
  File "<memimport>/sqlite3/dbapi2.py", line 28, in <module>
  File "<string>", line 130, in load_module
  File "<string>", line 97, in load_module
  File "<memimport>/sqlite3/__init__.py", line 24, in <module>
  File "<string>", line 130, in load_module
  File "<string>", line 97, in load_module
  File "<memimport>/lazagne/softwares/browsers/mozilla.py", line 9, in <module>
  File "<string>", line 130, in load_module
  File "<string>", line 97, in load_module
  File "<memimport>/lazagne/config/manageModules.py", line 6, in <module>
  File "<string>", line 130, in load_module
[-] tuple index out of range
```

I don't think the error comes from the lazagne code because it works well on my host. 
Here is my host configuration: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```
Thanks for your help.

**Comment by alxchk** [comment]
It's quite strange. I just check with Ubuntu 15.10/amd64 desktop + firefox. It work for me for fresh clone of pupy repo and amd64 payload from my templates (https://github.com/alxchk/pupy-binaries/blob/master/pupyx64.lin):
log

Please try to do fresh clone of @n1nj4sec mainstream repo, replace payload_templates with my ones, try to generate, upload and use. If it will not work, I'll upload debug templates.

**Comment by AlessandroZ** [comment]
Ok, my fault. 

Cloning the project works great. I don't know what happened, because my project was sync with the master of pupy. Anyway, I tried and everything is ok. 
@n1nj4sec, i let you close the pull request if it's ok for you. 

@alxchk, I don't know if it's easy to do (I didn't check the client code) but I noticed that launching the linux binary, the current path is always on the root directory ("/"). I needed to get the current directory for the sudo_alias module (https://github.com/n1nj4sec/pupy/blob/master/pupy/packages/linux/all/sudo_alias.py#L126)  so I noticed that. If you think, it's easy to do, it will be great to do it. 

Thanks both for your work, pupy is becoming really cool !

**Comment by alxchk** [comment]
Well, while reporting actual path to executable is clearly broken and should be fixed, I think this technique will not work anyway. Executable may and very likely be:
1. deleted
2. melted into another process (using ptrace or LD_PRELOAD)

**Pull request closed without merging**
