### PR TITLE
Network model fix (first attempt) and other things

### PR DESCRIPTION
**Pull request by alxchk**
Hi!
I have some spare time again, so finally get to the worst part of pupy (for me) - the network "stack".
Currently I'm playing with that what we have. First thing I'm trying to fix - the polling hell. Please take a look on the last commit. Probably something broken (so it's not intended to be merged right now), but on default (tcp/ssl) connection I have much better experience.

### CODE REVIEW

**Comment by AlessandroZ** [comment]
Why have you closed your pull request ? There were some good stuff in it.

**Comment by alxchk** [comment]
I likely should clean patches a bit. More than 50 changes is hard to merge, and some of them were completely rewritten in the end.

**Comment by AlessandroZ** [comment]
I understand, nice work by the way :)

**Comment by n1nj4sec** [comment]
it looks good don't hesitate to make a pull request when you have something more or less stable I can look at :) good job

**Pull request closed without merging**
