### PR TITLE
A lot of things

### PR DESCRIPTION
**Pull request by alxchk**
Most important changes:
- Reworked rpyc connections (again). Fix issues with nested (recursive) sync calls. Previously pupy hang on various places, now it just works. Cost - +1 thread per blocking call ( usually just 1 new thread ). 
- Brine/obtain monkey-patched to reduce size of newly created temporary strings. In some cases this will keep python heap arena small ( previously - up to 120 MB, now - around 25-30 MB)
- UDP support using KCP (https://github.com/skywind3000/kcp)
- Inbound proxy support (something like socks)
- Rework Cmd handler to be more abstract. In some (distant?) future this will allow to add another handlers simpler. Idea is (at least) to migrate to prompt toolkit.
- Cmd commands are now modular. Completion support was updated a bit, but still is far from being perfect (subparsers are not supported).
- Linux/windows/android build migrated to docker. Build has 3 stages now: toolchain -> environment -> pupy. This allows to fit to travis timings. Also it's much easier to do local rebuild.
- A lot of fixes, small features and bugs introduced.

Some rarely used (by me) modules, like tcpdump, may be broken.

Looks like upstream project is dead, isn't it?

### CODE REVIEW

**Comment by n1nj4sec** [comment]
nice :) I will test your PR soon ;) The project is not dead, I just don't have much time to work on it.

**Review by sexyscruffles — APPROVED** [review]

**Comment by quentinhardy** [comment]
Thank you for the work +1

**Comment by AlessandroZ** [comment]
Hi, 

I have a question about some changes you have done. I don't understand the purpose of the [proxy](https://github.com/alxchk/pupy/tree/unstable/pupy/proxy) directory. These files are loaded to the client or are they used to proxify the server ? And I'm interested to understand how do you use these files. Thanks to help me to understand. 

Another thing, right now, I do not use pupy on my desk but on a server that I share with other persons. And I have noticed, that pupy is not designed to work with multiple users. Maybe we should think about implementing this feature. I had to patch the source code to launch multiple pupy servers because right now, it is not possible, the web server listens on a [hardcoded](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/pupylib/PupyWeb.py#L31) port.

So maybe it would be interesting to implement an api or something like that (not necessary a web gui) to communicate with multiple users on an unique daemon. In my point of view, this is something, we should 
 think about a solution.

**Comment by alxchk** [comment]
> I don't understand the purpose of the proxy directory

The proxy goes to the trusted server and works as listener for inbound connections.
I.e. 
You -----> [ Trusted server :1337 ] <----- payload
It's only for communication, so your keys etc stays on pupysh (only exception is SSL).
The purpose is to ensure low latency for KCP (which will be converted by proxy to TCP) and solve various issues with NAT in enterprise environment (i.e. when there is no router with upnp which will setup port mappings for you).

> had to patch the source code to launch multiple pupy servers because right now, it is not possible, the web server listens on a hardcoded port.

Right now pupysh in alxchk/pupy can do multiple listeners (I don't use that stuff with oneliners and rest like this, so it's only about listeners), but for another purpose - to be able to communicate via different encapsulation protocols. It means that it's not possible to start multiple listeners for the same protocol for now. 

> And I have noticed, that pupy is not designed to work with multiple users.
> So maybe it would be interesting to implement an api or something like that (not necessary a web gui) to communicate with multiple users on an unique daemon. In my point of view, this is something, we should
think about a solution.

Technically pupysh can be separated to daemon part and client part. In alxchk/pupy almost finished separation handler from server, so likely client-server approach may be done.
I'm not interested in this right now, and likely will work on "virtual sockets" in case I'll have spare time.
So it's up to you (how) to do this ^^ But in case you really going to do this let's discuss to build right architecture.

**Comment by AlessandroZ** [comment]
Thanks for your answer. I will try your proxy when I would have some time, it looks cool. 

If I understood well, you put the proxy on a server you control with the SSL configuration. You say to the client to connect to the proxy and the proxy will redirect the traffic to us where the pupy server is installed (in our desk for example). 

> so your keys etc stays on pupysh (only exception is SSL) 

It means that the network is decrypted on the server and send it back to our desk in cleartext (I suppose no, but I try to find the reason to add the SSL configuration). 
Why adding the SSL configuration on the server instead of forwarding the traffic as a classic proxy (such as a TCP raw) ? 

> But in case you really going to do this let's discuss to build right architecture

I agree, I won't change the entire architecture without discussing about a good way to do it. Right now, I do not have time at all, but I will think about it.

**Comment by alxchk** [comment]
> It means that the network is decrypted on the server and send it back to our desk in cleartext (I suppose no, but I try to find the reason to add the SSL configuration).
Why adding the SSL configuration on the server instead of forwarding the traffic as a classic proxy (such as a TCP raw) ?

Actually I don't use SSL at all, and this was added because I was uncomfortable to have ssl over ssl.... :D

And yes, pupy to proxy goes over SSL with pregenerated  CA/Client/Server certs to not to reinvent a wheel :)

**Comment by AlessandroZ** [comment]
> I was uncomfortable to have ssl over ssl

Ahaha understood :)

**Pull request merged**
